### ISSUE TITLE
Datasets availability

### ISSUE THREAD

**Issue by Nnerri** [lifangda01/AdaptiveSupervisedPatchNCE#2]
Hello,

Thank you so much for the method and the publication of your dataset ! 

However, I don't find any data on the Google Drive link you gave, and I am not sure on how to use the Baidu Cloud? 

Could you give some specifics about how to download that data ? 

Thank you so much

**Comment by lifangda01** [comment]
Thank you so much for point this out!! It was an error on our side.

You should be able to access the data via the Google Drive link now.
