### ISSUE TITLE
Patch size for NCELoss.

### ISSUE THREAD

**Issue by boqchen** [lifangda01/AdaptiveSupervisedPatchNCE#4]
Hi Fangda,

Thanks for the great work!

I have a question regarding the patch size of the patches selected to calculate the NCELoss. Based on the code here [https://github.com/lifangda01/AdaptiveSupervisedPatchNCE/blob/master/models/networks.py#L551-L568](url) it seems like each patch only corresponds to a single pixel. Can you elaborate more on this?

Thanks in advance!

**Comment by lifangda01** [comment]
Hi! I think it is one "pixel" at any feature level. When the input feature is the raw image, then it is literally one pixel. However, when the input is a deep feature map, that one "pixel" basically is the aggregation of information of a patch (at the image level) spanned by the receptive field. Hope this helps!

**Comment by boqchen** [comment]
Hi Fangda,

Thanks for your prompt reply. That explains my question.

Do you also have some insights of how to choose feature layers? E.g., if I want to use u-net as the generator, which layers could be good for calculating NCELoss.

Thanks!

**Comment by lifangda01** [comment]
My experience is that the network is more stable to train and results are better when you use a pyramid of feature levels, that means going from pixel level to deep feature level. This is the case when comparing to eg just using deep feature levels, but could vary from application to application. Intuitively applying the NCEloss on deeper levels should make the output more consistent with the GT on a higher semantic level.

**Comment by boqchen** [comment]
Thanks for you insights Fangda!

However, when you mention deeper layers, it is more straightforward for ResNet-based generator. I was wondering, for a UNet-based pix2pix model, what could be seen as "deeper features". More specifically, since UNet has a encoding and decoding path, and there is a skip connection in between, while decoder blocks are deeper, the output features of them are concat with, however, shallower features from encoder. The deeper the decoder block is, the shallower feature it is concat with. Since you does not experiment on UNet-based pix2pix model in the paper, I was wondering if you could shed some light on this?

Thanks!

**Comment by lifangda01** [comment]
Hi Boqi, by "deeper features" I actually meant the features after more ResBlocks / downsamplings in the _encoder_ only. The features in the decoder half are not considered for the PatchNCE losses. At least that is what I did with the current architecture and I wouldn't expect it to be very different should an UNet is used. Hope this helps!

**Comment by boqchen** [comment]
Thanks Fangda! This helps a lot!
