### ISSUE TITLE
BCI dataset cannot be trained properly

### ISSUE THREAD

**Issue by ccitachi** [lifangda01/AdaptiveSupervisedPatchNCE#5]
i use the BCI dataset which you mentioned in your paper.And i start train according to your guidence. But the network  have mode collapse suddenly in the second epoch. The G_Gan is 1.000,and the D_real is 0.000. D_fake is also 0.000.  The output is very different with the real label ,which has various color. 
What parameters can I set to adjust the training on this BCI dataset. Thanks

**Comment by lifangda01** [comment]
Hi! In my experiments the BCI dataset is indeed a tough / more sensitive one to train. In its original form, the brightness levels of the HE and IHC are very disparate, adding to the GT pair inconsistencies. That is the reason for me to first normalize the brightness levels of the BCI images as mentioned in the paper. Alternatively, you could also try some other form of input normalization. That seemed to help in my case.
