### ISSUE TITLE
Questions regarding inference image size

### ISSUE THREAD

**Issue by boqchen** [lifangda01/AdaptiveSupervisedPatchNCE#8]
Hi Fangda,

In the paper, you mentioned during the training, you random crop the images so that the input size is 512^2 instead of 1024^2. I was wondering what is the size then used for the inference. If the image size is 1024^2 used for inference, how do you make it compatible with the model trained on 512^2 input. Is there any resizing of images before inference? If so, will this create a resolution mismatch? 

Thanks in advance for your time and consideration.

Best,
Boqi

**Comment by lifangda01** [comment]
Hello Boqi, for inference I did use 1024x1024. Since the simple generator architecture I used is purely convolutional (i.e. without modules such as self-attention), training on one size and inference on another wasn't really a problem.
