### ISSUE TITLE
Single dataset testing 

### ISSUE THREAD

**Issue by prateek1621** [lifangda01/AdaptiveSupervisedPatchNCE#9]
Hi can you release or share code for single dataset conversion . In` mist_launcher.py `there are comments that suggests we can use particular mode of dataset like `dataset_mode='single',  # chooses how datasets are loaded. [unaligned | aligned | single | colorization]'` . so can you share the code for each case . 

thank you

**Comment by lifangda01** [comment]
Sorry about the confusion -- since I only used `aligned` in this repo, I didn't put code there for other dataset modes for brevity. Nonetheless, you can find them here for your own needs: https://github.com/taesungp/contrastive-unpaired-translation/tree/master/data
